### ISSUE TITLE
Some transactions remain blocked with enough gas price

### ISSUE THREAD

**Issue by aweneagle** [ethereum-optimism/op-geth#123]
#### System information

Geth version: `v1.101200.0`
OS & Version: Linux

Background: We deployed a set of op-geth nodes as p2p layer before miner nodes for high availability. All transactions go to the p2p nodes first, then broadcasted(or reannounced) to the miner nodes later.

#### Expected behaviour
All transactions with enough price and correct nonce should be mined when the miner's pool is empty and gas price goes down.

#### Actual behaviour
Some transactions are stuck in the previous node's pool forever after a traffic jam.

#### Steps to reproduce the behaviour
1. Prepare some addresses (let's say 100k+)
1. Try to send transactions between them, in a high throughput(say 4k+/s tps), and keep it for a while (say 30mins)
2. Make sure to trigger the traffic jam. (By watching meter indicated whether the miner's pool size has reach the limit or not)
3. After the load testing finished, there might be some transactions stuck in the p2p nodes forever.

We found the root cause here :
they are caught in this [underpriced buffer](
https://github.com/ethereum-optimism/op-geth/blob/368310232f16b7697d3a79ea7f946f0b2b21ab3f/eth/fetcher/tx_fetcher.go#L305). After adding a frequent cleaner to this buffer, the blocking issue disappeared.

So, i am wondering that, maybe we should make this buffer refresh frequently? or just remove it? 
When the traffic is jamming, some  transactions may be rejected as 'underpriced', and might be rejected forever even the chain's gas price has went down, unless other 'underpriced' transaction replace it.  it's seems unfair.

**Comment by protolambda** [comment]
This is not specific to op-geth. Can you open an issue in the upstream L1 go-ethereum repo (and first check if there are similar / duplicate issues), and then link that here?

**Comment by aweneagle** [comment]
ok, thanks for your suggestion.

**Comment by aweneagle** [comment]
referenced by l1 issue [#issue28018](https://github.com/ethereum/go-ethereum/issues/28018)
