### ISSUE TITLE
Op geth

### ISSUE THREAD

**Issue by manjaneqx** [ethereum-optimism/op-geth#169]
#### System information

Geth version: `geth version`
CL client & version: e.g. lighthouse/nimbus/prysm@v1.0.0
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by protolambda** [comment]
Please provide detailed information when opening an issue. Empty issues like these will be closed. Thank you.
