### ISSUE TITLE
http config maxRequestContentLength has not been released yet

### ISSUE THREAD

**Issue by wangjiangw** [ethereum-optimism/op-geth#173]
i have seen that the maxRequestContentLength was changed to 1024 * 1024 * 32，but in latest version （v1.101301.1）the config still 1024 * 1024 * 5

![image](https://github.com/ethereum-optimism/op-geth/assets/7013043/d49b9594-bc5b-4ecf-89b1-410537d85034)

![image](https://github.com/ethereum-optimism/op-geth/assets/7013043/72092678-9e22-454d-9793-4fd1688a6d78)

**Comment by protolambda** [comment]
Release candidates for `v1.101304.0` are in progress, this change will be available by default soon. In the meantime, if you are experiencing any syncing issues, please use the websocket Engine API endpoint.
