### ISSUE TITLE
Expose flag to change hardcoded block length for state pruner

### ISSUE THREAD

**Issue by kaliubuntu0206** [ethereum-optimism/op-geth#178]
# Rationale

To avoid running op-geth with archive mode, op-geth should be able to set length to remain state of recent blocks by flag

Example for hardcoded values

https://github.com/ethereum-optimism/op-geth/blob/optimism/core/blockchain.go#L106
https://github.com/ethereum-optimism/op-geth/blob/optimism/core/state/pruner/pruner.go#L257
https://github.com/ethereum-optimism/op-geth/blob/optimism/core/state/statedb.go#L1262

**Comment by kaliubuntu0206** [comment]
@protolambda Due to the fact that geth codebase is somewhat complex for moving hardcoded values, I just found a flag `--history.state` but could it accomplish the goal that we want?

**Comment by kaliubuntu0206** [comment]
I asked some questions to Geth devs and I think we could find an alternative approach https://github.com/ethereum-optimism/optimism/issues/7984.

**Comment by root0x0** [comment]
`--history.state` flag does not work for me? still `missing trie node`

**Comment by kaliubuntu0206** [comment]
@root0x0 It doesn't, when I asked Geth devs about the functionality and I have heard it is being prepared. So, unless running op-reth with custom pruned flags running an archive node would be an requirement. ( Or, running the proposer with sequencer could be a nice hack since if the sequencer goes offline the L2 chain will not be able to create new blocks which proposer doesn't need to fetch old blocks as well )
