### ISSUE TITLE
Snap Sync: Add a netrestrict flag which only applies to the txpool

### ISSUE THREAD

**Issue by trianglesphere** [ethereum-optimism/op-geth#194]
We want to be able to separate the txpool part of the eth P2P namespace from the block & receipt fetching.

See: https://github.com/ethereum/devp2p/blob/master/caps/eth.md

This feature should disable the txpool by default & should opt-in to sharing the txpool to specific CIDR network masks.

**Comment by mslipper** [comment]
If we don't do this, it would require us to spin up a second set of replicas that don't have a tx pool but are peered with our replicas. This would be the initial set of nodes people can snap sync to.

**Comment by mslipper** [comment]
Josh is leaning towards the netrestrict flag - will leave up to him for a decision.

**Comment by trianglesphere** [comment]
Cancelling this in favor of having a dedicated node that has the txpool disable flaged on.
