### ISSUE TITLE
Does op-geth work with path-based state scheme?

### ISSUE THREAD

**Issue by celochoi** [ethereum-optimism/op-geth#351]
Path-based state scheme was introduced in geth version 1.13.0 and became the default in version 1.14.0. I understand that op-geth follows geth closely, but I'm curious if this option is also available in op-geth. Has there been any internal experimentation related to this feature?

**Comment by sebastianst** [comment]
Yes, it's working and we use it extensively. Note that `path` is only available for full nodes, not archival.
