### ISSUE TITLE
Enable the GitHub Slack integration 

### ISSUE THREAD

**Issue by Madhulearn6** [ethereum-optimism/op-geth#356]
Hello Team,

I’m reaching out on behalf of [Lisk](https://lisk.com/). We’re currently a member of the [OP Superchain ecosystem](https://www.superchain.eco/ecosystem-chains/lisk).

We currently have the [lisk-node](https://github.com/LiskHQ/lisk-node) repo which currently allows operators to conveniently run their nodes on Lisk L2.

To help our integration partners operate their nodes on the Lisk L2 we currently have the [lisk-node](https://github.com/LiskHQ/lisk-node) repo. Based on our recent challenges with the Fjord upgrade, we have established an internal process to keep ourselves up-to-date based on your repo updates. An integral part of the long-term solution involves setting up notifications on our Slack channels which cannot be achieved without you enabling the integration on your GitHub repo.

So, could we please request you to enable the [GitHub Slack integration](https://github.com/integrations/slack) on your repo to help us be more efficient?
FYR, the [ethereum-optimism/optimism](https://github.com/ethereum-optimism/optimism) repo already supports this integration.

Kindly let us know if you need any further information from our end.
We anticipate your support and thank you in advance.

Best regards,
Lisk Team

**Comment by tynes** [comment]
Hello @Madhulearn6, this should be addressed now

**Comment by sameersubudhi** [comment]
Thank you very much @tynes. The issue can now be closed from our end 🙏
