### ISSUE TITLE
Full node latest snapshot

### ISSUE THREAD

**Issue by circus0988** [ethereum-optimism/op-geth#374]
# Rationale

Full syncing from year-old snapshot is too slow and archive snapshot is too heavy. Please, provide latest full non-archival snapshot in https://datadirs.optimism.io/.

**Comment by protolambda** [comment]
I'll check with infra if updated snapshots can be provided.

As alternative, try to sync with snap-sync, it's quite fast to get up and running: https://docs.optimism.io/builders/node-operators/management/snap-sync

**Comment by circus0988** [comment]
Hi! So, is it possible?

**Comment by 3eph1r0th** [comment]
You can download fresh Optimism blockchain (both mainnet and testnet) snapshot here: https://www.publicnode.com/snapshots#optimism

**Comment by protolambda** [comment]
https://datadirs.optimism.io/  provides updated archive snapshots now. For full-node it's recommended to use snap-sync instead.
