### ISSUE TITLE
State changes for fee addresses missing in prestate tracer result

### ISSUE THREAD

**Issue by Pangssu** [ethereum-optimism/op-geth#410]
Hi, I'm Pang from Kroma.
When calling the `debug_traceTransaction` API with the prestate tracer and set `diffMode` to true, balance changes for fee addresses are not included in the results. 
The reason is that the tracer doesn't look up fee addresses.
Is this the intended behavior?

**Comment by protolambda** [comment]
This is not intended behavior. The fee-addresses should be included in the diff. PRs are welcome to introduce this behavior. That said, the fee addresses never change, so I hope you found a work around in the mean time.

**Comment by Pangssu** [comment]
@protolambda I opened PR #444.
